# Generated by Django 5.2.3 on 2025-06-25 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMusicPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(help_text='YouTube Video ID', max_length=50)),
                ('video_title', models.CharField(max_length=255)),
                ('preference_type', models.CharField(choices=[('liked', '좋아요'), ('disliked', '싫어요'), ('saved', '보관')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'video_id', 'preference_type')},
            },
        ),
    ]
