# Generated by Django 5.2 on 2025-06-15 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='사용자가 업로드한 음식 사진', null=True, upload_to='diet_images/%Y/%m/%d/')),
                ('text_input', models.TextField(blank=True, help_text='사용자가 글로 입력한 음식 내용 (예: 사과 1개, 닭가슴살 샐러드)')),
                ('analysis_result', models.JSONField(blank=True, help_text='OpenAI API의 분석 결과(JSON)를 저장', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
