# Generated by Django 5.2 on 2025-06-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('thumbnail', models.ImageField(upload_to='store_thumbnails/', verbose_name='썸네일')),
                ('product_link', models.URLField(verbose_name='상품 링크')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '추천 상품',
                'verbose_name_plural': '추천 상품 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
