# Generated by Django 5.2 on 2025-06-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='브랜드명')),
                ('link', models.URLField(verbose_name='브랜드 링크')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='brand_thumbnails/', verbose_name='썸네일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '추천 브랜드',
                'verbose_name_plural': '추천 브랜드 목록',
                'ordering': ['name'],
            },
        ),
    ]
