# Generated by Django 5.2 on 2025-06-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.CharField(choices=[('APPAREL', '의류'), ('EQUIPMENT', '장비'), ('SUPPLEMENTS', '보충제'), ('ACCESSORIES', '액세서리'), ('ETC', '기타')], default='ETC', max_length=20, verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='추천 브랜드 지정'),
        ),
        migrations.AddField(
            model_name='brand',
            name='short_description',
            field=models.CharField(blank=True, max_length=150, verbose_name='간단 설명'),
        ),
    ]
