# Generated by Django 5.2.3 on 2025-06-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_brand_category_brand_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='detailed_description',
            field=models.TextField(blank=True, null=True, verbose_name='상세 설명 (퀵 뷰용)'),
        ),
    ]
