# Generated by Django 5.2.3 on 2025-06-20 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_brand_detailed_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='태그명')),
            ],
            options={
                'verbose_name': '핵심 태그',
                'verbose_name_plural': '핵심 태그 목록',
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': '브랜드', 'verbose_name_plural': '브랜드 목록'},
        ),
        migrations.RemoveField(
            model_name='brand',
            name='short_description',
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='짧은 설명 (카드 표시용)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_brands', to=settings.AUTH_USER_MODEL, verbose_name='찜한 사용자'),
        ),
        migrations.AddField(
            model_name='brand',
            name='promotion_info',
            field=models.CharField(blank=True, max_length=50, verbose_name="프로모션 정보 (예: '20% 할인')"),
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.CharField(choices=[('NUTRITION', '보충제'), ('CLOTHING', '의류'), ('EQUIPMENT', '용품'), ('FOOD', '식품')], max_length=20, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='detailed_description',
            field=models.TextField(blank=True, default='', verbose_name='상세 설명 (모달 표시용)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='추천 브랜드 여부'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='link',
            field=models.URLField(verbose_name='공식 사이트 링크'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='brand_thumbnails/', verbose_name='썸네일 이미지'),
        ),
        migrations.AddField(
            model_name='brand',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='brands', to='store.tag', verbose_name='핵심 태그'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], verbose_name='평점')),
                ('content', models.TextField(verbose_name='리뷰 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.brand', verbose_name='브랜드')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '브랜드 리뷰',
                'verbose_name_plural': '브랜드 리뷰 목록',
                'ordering': ['-created_at'],
                'unique_together': {('brand', 'user')},
            },
        ),
    ]
