# Generated by Django 5.2.3 on 2025-06-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_tag_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.CharField(choices=[('NUTRITION', '보충제'), ('CLOTHING', '의류'), ('EQUIPMENT', '용품'), ('ACCESSORIES', '잡화/악세사리'), ('FOOD', '식품'), ('ETC', '기타')], db_index=True, default='ETC', max_length=20, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='link',
            field=models.URLField(verbose_name='브랜드 링크'),
        ),
    ]
