# Generated by Django 5.2.3 on 2025-06-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_brand_category_alter_brand_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.CharField(choices=[('APPAREL', '의류'), ('EQUIPMENT', '운동용품'), ('SUPPLEMENTS', '보충제'), ('ACCESSORIES', '잡화/악세사리'), ('ETC', '기타')], db_index=True, default='ETC', max_length=20, verbose_name='카테고리'),
        ),
    ]
