# Generated by Django 5.2.3 on 2025-06-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_brand_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='카테고리 코드')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리명')),
            ],
            options={
                'verbose_name': '브랜드 카테고리',
                'verbose_name_plural': '브랜드 카테고리 목록',
            },
        ),
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.AlterField(
            model_name='brand',
            name='promotion_info',
            field=models.CharField(blank=True, max_length=50, verbose_name='프로모션 정보'),
        ),
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='brands', to='store.brandcategory', verbose_name='카테고리'),
        ),
    ]
