# Generated by Django 5.2.3 on 2025-06-24 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_brandcategory_remove_brand_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyShapeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_image', models.ImageField(upload_to='body_analysis_images/')),
                ('body_shape', models.CharField(blank=True, choices=[('HOURGLASS', '모래시계형'), ('TRIANGLE', '삼각형 (서양배형)'), ('INVERTED_TRIANGLE', '역삼각형'), ('RECTANGLE', '직사각형'), ('OVAL', '타원형 (사과형)')], max_length=20, null=True)),
                ('analysis_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
