# Generated by Django 5.2.3 on 2025-06-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_bodyshapeanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_shape', models.CharField(choices=[('HOURGLASS', '모래시계형'), ('TRIANGLE', '삼각형 (서양배형)'), ('INVERTED_TRIANGLE', '역삼각형'), ('RECTANGLE', '직사각형'), ('OVAL', '타원형 (사과형)')], max_length=20, unique=True)),
                ('recommended_fits', models.TextField(help_text='추천하는 옷 스타일 (예: A라인 스커트, 와이드 팬츠, 보트넥 티셔츠)을 쉼표로 구분하여 입력')),
                ('style_tips', models.TextField(help_text='스타일링 팁 요약')),
            ],
        ),
    ]
