# Generated by Django 5.2.3 on 2025-06-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_clothingrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyshapeanalysis',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodyshapeanalysis',
            name='skeleton_image',
            field=models.ImageField(blank=True, null=True, upload_to='body_analysis/skeleton/'),
        ),
        migrations.AddField(
            model_name='bodyshapeanalysis',
            name='style_tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodyshapeanalysis',
            name='source_image',
            field=models.ImageField(upload_to='body_analysis/source/'),
        ),
    ]
