# Generated by Django 5.2.3 on 2025-06-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_bodyshapeanalysis_recommendations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyshapeanalysis',
            name='analysis_image',
            field=models.ImageField(blank=True, null=True, upload_to='body_analysis/analysis_results/'),
        ),
    ]
