# Generated by Django 5.2.3 on 2025-07-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_bodyshapeanalysis_analysis_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyshapeanalysis',
            name='recommendations_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodyshapeanalysis',
            name='recommendations_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodyshapeanalysis',
            name='recommendations_ko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodyshapeanalysis',
            name='style_tips_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodyshapeanalysis',
            name='style_tips_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodyshapeanalysis',
            name='style_tips_ko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='짧은 설명 (카드 표시용)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_es',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='짧은 설명 (카드 표시용)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_ko',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='짧은 설명 (카드 표시용)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='detailed_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='상세 설명 (모달 표시용)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='detailed_description_es',
            field=models.TextField(blank=True, null=True, verbose_name='상세 설명 (모달 표시용)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='detailed_description_ko',
            field=models.TextField(blank=True, null=True, verbose_name='상세 설명 (모달 표시용)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='브랜드명'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_es',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='브랜드명'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_ko',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='브랜드명'),
        ),
        migrations.AddField(
            model_name='brand',
            name='promotion_info_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='프로모션 정보'),
        ),
        migrations.AddField(
            model_name='brand',
            name='promotion_info_es',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='프로모션 정보'),
        ),
        migrations.AddField(
            model_name='brand',
            name='promotion_info_ko',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='프로모션 정보'),
        ),
        migrations.AddField(
            model_name='brandcategory',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='카테고리명'),
        ),
        migrations.AddField(
            model_name='brandcategory',
            name='name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='카테고리명'),
        ),
        migrations.AddField(
            model_name='brandcategory',
            name='name_ko',
            field=models.CharField(max_length=50, null=True, verbose_name='카테고리명'),
        ),
        migrations.AddField(
            model_name='clothingrecommendation',
            name='recommended_fits_en',
            field=models.TextField(help_text='추천하는 옷 스타일 (예: A라인 스커트, 와이드 팬츠, 보트넥 티셔츠)을 쉼표로 구분하여 입력', null=True),
        ),
        migrations.AddField(
            model_name='clothingrecommendation',
            name='recommended_fits_es',
            field=models.TextField(help_text='추천하는 옷 스타일 (예: A라인 스커트, 와이드 팬츠, 보트넥 티셔츠)을 쉼표로 구분하여 입력', null=True),
        ),
        migrations.AddField(
            model_name='clothingrecommendation',
            name='recommended_fits_ko',
            field=models.TextField(help_text='추천하는 옷 스타일 (예: A라인 스커트, 와이드 팬츠, 보트넥 티셔츠)을 쉼표로 구분하여 입력', null=True),
        ),
        migrations.AddField(
            model_name='clothingrecommendation',
            name='style_tips_en',
            field=models.TextField(help_text='스타일링 팁 요약', null=True),
        ),
        migrations.AddField(
            model_name='clothingrecommendation',
            name='style_tips_es',
            field=models.TextField(help_text='스타일링 팁 요약', null=True),
        ),
        migrations.AddField(
            model_name='clothingrecommendation',
            name='style_tips_ko',
            field=models.TextField(help_text='스타일링 팁 요약', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ko',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='상품명'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='상품명'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ko',
            field=models.CharField(max_length=100, null=True, verbose_name='상품명'),
        ),
        migrations.AddField(
            model_name='review',
            name='content_en',
            field=models.TextField(null=True, verbose_name='리뷰 내용'),
        ),
        migrations.AddField(
            model_name='review',
            name='content_es',
            field=models.TextField(null=True, verbose_name='리뷰 내용'),
        ),
        migrations.AddField(
            model_name='review',
            name='content_ko',
            field=models.TextField(null=True, verbose_name='리뷰 내용'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='태그명'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_es',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='태그명'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ko',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='태그명'),
        ),
    ]
