# Generated by Django 5.2.3 on 2025-07-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_bodyshapeanalysis_recommendations_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='detailed_description_en',
            field=models.TextField(blank=True, help_text='영어 상세 설명', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='detailed_description_es',
            field=models.TextField(blank=True, help_text='스페인어 상세 설명', null=True),
        ),
    ]
