# Generated by Django 5.2 on 2025-06-14 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('muscle_group', models.CharField(blank=True, max_length=50, null=True)),
                ('gif_url', models.URLField(default='https://via.placeholder.com/100x100.png?text=No+Image')),
                ('default_sets', models.IntegerField(default=3)),
                ('default_reps', models.IntegerField(default=12)),
                ('exercise_type', models.CharField(choices=[('strength', '근력'), ('cardio', '유산소')], default='strength', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField(help_text='단위: kg')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.exercise')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.routine')),
            ],
            options={
                'unique_together': {('routine', 'exercise')},
            },
        ),
        migrations.AddField(
            model_name='routine',
            name='exercises',
            field=models.ManyToManyField(through='routine.RoutineExercise', to='routine.exercise'),
        ),
    ]
