# Generated by Django 5.2 on 2025-06-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='default_reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='default_sets',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='level',
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='단위: 분', null=True),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='단위: kg', null=True),
        ),
    ]
