# Generated by Django 5.2 on 2025-06-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_remove_exercise_default_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='exercises',
            field=models.ManyToManyField(related_name='routines', through='routine.RoutineExercise', to='routine.exercise'),
        ),
    ]
