# Generated by Django 5.2 on 2025-06-18 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_alter_routine_exercises'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routineexercise',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('strength', '근력'), ('cardio', '유산소')], default='strength', help_text='운동의 종류 (근력/유산소)', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='gif_url',
            field=models.URLField(default='https://via.placeholder.com/100x100.png?text=No+Image', help_text='운동 동작 GIF URL', max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(blank=True, help_text='운동이 주로 자극하는 부위', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(help_text='운동의 고유한 이름', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='exercises',
            field=models.ManyToManyField(related_name='exercise_routines', through='routine.RoutineExercise', to='routine.exercise'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='운동 시간 (분)'),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='반복 횟수'),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='세트'),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='무게 (kg)'),
        ),
    ]
