# Generated by Django 5.2 on 2025-06-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_alter_routineexercise_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, help_text='운동의 주요 자극 부위 및 방법에 대한 상세 설명', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='precautions',
            field=models.TextField(blank=True, help_text='운동 시 주의해야 할 점이나 흔한 실수', null=True),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='description',
            field=models.TextField(blank=True, help_text='AI가 생성한 운동 상세 설명', null=True),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='precautions',
            field=models.TextField(blank=True, help_text='AI가 생성한 운동 주의사항', null=True),
        ),
    ]
