# Generated by Django 5.2.3 on 2025-06-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0006_workoutlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description_en',
            field=models.TextField(blank=True, help_text='운동 설명 (영어)', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='description_es',
            field=models.TextField(blank=True, help_text='운동 설명 (스페인어)', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_group_en',
            field=models.CharField(blank=True, help_text='운동 부위 (영어)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_group_es',
            field=models.CharField(blank=True, help_text='운동 부위 (스페인어)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='name_en',
            field=models.CharField(blank=True, help_text='운동 이름 (영어)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='name_es',
            field=models.CharField(blank=True, help_text='운동 이름 (스페인어)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='precautions_en',
            field=models.TextField(blank=True, help_text='운동 주의사항 (영어)', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='precautions_es',
            field=models.TextField(blank=True, help_text='운동 주의사항 (스페인어)', null=True),
        ),
    ]
