# Generated by Django 5.2.3 on 2025-06-19 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='업적 이름')),
                ('title_reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='보상 칭호')),
                ('description', models.TextField(verbose_name='업적 설명')),
                ('category', models.CharField(choices=[('DIET', '식단'), ('WORKOUT', '운동'), ('CONSISTENCY', '꾸준함'), ('EXPLORE', '탐험'), ('CHATBOT', '챗봇')], default='WORKOUT', max_length=20, verbose_name='카테고리')),
                ('is_secret', models.BooleanField(default=False, verbose_name='숨겨진 업적 여부')),
                ('codename', models.CharField(blank=True, help_text='개발용 고유 코드', max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='달성 일시')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement', verbose_name='달성한 업적')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
