# Generated by Django 5.2.3 on 2025-06-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_populate_final_achievements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': '업적', 'verbose_name_plural': '업적 목록'},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'verbose_name': '사용자 달성 업적', 'verbose_name_plural': '사용자 달성 업적 목록'},
        ),
        migrations.AddField(
            model_name='achievement',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='업적 설명 (영어)'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='업적 설명 (스페인어)'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='업적 이름 (영어)'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='업적 이름 (스페인어)'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='title_reward_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='보상 칭호 (영어)'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='title_reward_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='보상 칭호 (스페인어)'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='codename',
            field=models.CharField(blank=True, help_text='개발용 고유 코드', max_length=100, null=True, unique=True, verbose_name='코드네임'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(verbose_name='업적 설명 (한국어)'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='업적 이름 (한국어)'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title_reward',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='보상 칭호 (한국어)'),
        ),
    ]
