# Generated by Django 5.2.3 on 2025-06-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_alter_achievement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('DIET', '식단'), ('WORKOUT', '운동'), ('CONSISTENCY', '꾸준함'), ('EXPLORE', '탐험'), ('CHATBOT', '챗봇')], default='WORKOUT', max_length=20),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='codename',
            field=models.CharField(blank=True, help_text='개발용 고유 코드', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title_reward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title_reward_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title_reward_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
