# Generated by Django 5.2.3 on 2025-06-30 03:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatbotinteractionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatconversation',
            options={'ordering': ['-created_at'], 'verbose_name': '챗봇 대화', 'verbose_name_plural': '챗봇 대화 목록'},
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='full_text',
            field=models.TextField(verbose_name='전체 대화 내용'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='is_custom_title',
            field=models.BooleanField(default=False, verbose_name='사용자 지정 제목 여부'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='summary_text',
            field=models.TextField(blank=True, null=True, verbose_name='요약 내용'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='summary_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='대화 제목'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
