# Generated by Django 5.2.1 on 2025-06-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FitnessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experience", models.CharField(max_length=10)),
                ("goal", models.CharField(max_length=50)),
                ("goal_text", models.CharField(blank=True, max_length=100, null=True)),
                ("frequency", models.IntegerField()),
                ("weight_unit", models.CharField(max_length=10)),
                ("distance_unit", models.CharField(max_length=10)),
                ("source", models.CharField(max_length=20)),
                ("weight", models.FloatField()),
                ("height", models.FloatField()),
                ("birth", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("types", models.CharField(max_length=200)),
                ("gym", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="HealthSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blood_type", models.CharField(max_length=20)),
                ("allergy", models.JSONField()),
                ("allergy_details", models.TextField(blank=True, null=True)),
                ("chronic_disease", models.JSONField()),
                ("chronic_disease_details", models.TextField(blank=True, null=True)),
                ("surgery_history", models.TextField(blank=True, null=True)),
                ("current_medication", models.TextField(blank=True, null=True)),
                ("supplements", models.TextField(blank=True, null=True)),
                ("smoking_status", models.CharField(max_length=30)),
                ("smoking_period", models.IntegerField(blank=True, null=True)),
                ("smoking_amount", models.IntegerField(blank=True, null=True)),
                ("drinking_frequency", models.CharField(max_length=30)),
                (
                    "drinking_amount",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("family_history", models.JSONField()),
                ("family_history_details", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
