# Generated by Django 5.2.3 on 2025-06-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_healthsurvey_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("account", "계정 관리"),
                            ("routine", "운동 루틴"),
                            ("diet", "식단"),
                            ("feature", "기능 문의"),
                            ("bug", "오류/버그 신고"),
                            ("etc", "기타"),
                        ],
                        max_length=20,
                        verbose_name="문의 유형",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="답변받을 이메일"),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="제목")),
                ("message", models.TextField(verbose_name="문의 내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="접수 시간"),
                ),
                (
                    "is_answered",
                    models.BooleanField(default=False, verbose_name="답변 완료 여부"),
                ),
            ],
            options={
                "verbose_name": "1:1 문의",
                "verbose_name_plural": "1:1 문의 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
