# Generated by Django 5.2.3 on 2025-06-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_inquiry_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="answer",
            field=models.TextField(blank=True, null=True, verbose_name="답변 내용"),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="answered_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="답변 시간"),
        ),
    ]
