# Generated by Django 5.2.3 on 2025-07-02 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_inquiry_answer_inquiry_answered_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='체중 (kg)')),
                ('skeletal_muscle_mass', models.FloatField(blank=True, null=True, verbose_name='골격근량 (kg)')),
                ('body_fat_mass', models.FloatField(blank=True, null=True, verbose_name='체지방량 (kg)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '일별 건강 지표',
                'verbose_name_plural': '일별 건강 지표',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
