# Generated by Django 5.2 on 2025-06-14 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='job_post',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='NotificationPreference',
        ),
    ]
