# Generated by Django 5.2 on 2025-06-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='body_fat_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skeletal_muscle_mass',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
