# Generated by Django 5.2.3 on 2025-06-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bodycompositionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/avatar-default.jpeg', upload_to='profile_pics/'),
        ),
    ]
