# Generated by Django 5.2.3 on 2025-06-20 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_image'),
        ('achievements', '0002_populate_final_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_title',
            field=models.ForeignKey(blank=True, help_text='사용자가 설정한 대표 칭호', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_by_profile', to='achievements.userachievement'),
        ),
    ]
