# Generated by Django 5.2 on 2025-06-05 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatconversation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='is_custom_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='summary_title',
            field=models.CharField(default='새 대화', max_length=200),
        ),
    ]
